<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Spring Boot User Authentication</title>
</head>
<body>
<form action="/sign-in" method="post">
    <lable>Username</lable>
    <label for="username"></label><input type="text" id="username" name="username"/>
    <lable>Password</lable>
    <label for="password"></label><input type="password" id="password" name="password">
    <input type="submit">
</form>
</body>
</html>